### ISSUE TITLE
Endpoint for listing out "bad"-packages

### ISSUE THREAD

**Issue by andmos** [andmos/Stratos#5]
There should be an API endpoint for listing out packages that has failed when installing. "bad" packages is located in `%chocolateyInstall%\lib-bad`. @ferventcoder - is there any CLI option for listing out bad packages?

**Comment by ferventcoder** [comment]
@andmos nada. They are considered not installed. Failures are reported during install and expected to be looked into based on the reported failure of the install.

**Comment by andmos** [comment]
May not be an issue. Most provisioning tools catch this up - and ignoring package-errors is bad in the first place. Closing.
